# Proyecto 

In [1]:
import numpy as np
import pandas as pd

In [45]:
#Configuraciones de visualización
np.set_printoptions(suppress = True)

#Cargando data
datos = np.load('Data/proyecto_training_data.npy')

#Datos de entrenamiento - 80%
datosEntrenamiento = datos[0 : int(len(datos) * 0.80), ]

#Datos de prueba - 20%
datosPrueba = datos[int(len(datos) * 0.80): , ]

dfEntrenamiento = pd.DataFrame(datosEntrenamiento, columns = ['SalePrice', 'OverallQual', '1stFlrSF', 'TotRmsAbvGrd', 'YearBuilt', 'LotFrontage'])
dfPrueba = pd.DataFrame(datosPrueba, columns = ['SalePrice', 'OverallQual', '1stFlrSF', 'TotRmsAbvGrd', 'YearBuilt', 'LotFrontage'])

dfEntrenamiento

SalePrice  OverallQual  1stFlrSF  TotRmsAbvGrd  YearBuilt  LotFrontage
0      208500.0          7.0     856.0           8.0     2003.0         65.0
1      181500.0          6.0    1262.0           6.0     1976.0         80.0
2      223500.0          7.0     920.0           6.0     2001.0         68.0
3      140000.0          7.0     961.0           7.0     1915.0         60.0
4      250000.0          8.0    1145.0           9.0     2000.0         84.0
...         ...          ...       ...           ...        ...          ...
1163   108959.0          4.0    1258.0           6.0     1969.0         60.0
1164   194000.0          5.0    1432.0           5.0     1978.0          NaN
1165   233170.0          7.0    1502.0           7.0     2009.0         79.0
1166   245350.0          8.0    1694.0           7.0     2008.0         64.0
1167   173000.0          6.0     959.0           7.0     2000.0         58.0

[1168 rows x 6 columns]

In [28]:
# Datos estadísticos

np.nanmean(data, axis = 0))
print(np.nanmax(data, axis = 0))
print(np.nanmin(data, axis = 0))
print(np.nanmax(data, axis = 0) - np.nanmin(data, axis = 0))
print(np.nanstd(data, axis = 0))

[180921.19589041      6.09931507   1162.62671233      6.51780822
   1971.26780822     70.04995837]
[755000.     10.   4692.     14.   2010.    313.]
[34900.     1.   334.     2.  1872.    21.]
[720100.      9.   4358.     12.    138.    292.]
[79415.29188607     1.38252284   386.4553223      1.62483655
    30.19255881    24.27463945]
